#!/bin/bash

mkdir Desktop
cd Desktop
wget https://www.dropbox.com/s/dl0vxdgb5qttdee/EECS%20Day%20CS%20Lab.zip?dl=1
unzip EECS\ Day\ CS\ Lab.zip?dl=1
rm -rf __MACOSX
rm -f EECS\ Day\ CS\ Lab.zip?dl=1
cd EECS\ Day\ CS\ Lab/
./install
exit
